import Head from 'next/head';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import Mapping from '../components/Mapping';
import Booking from '../components/Booking';
import Footer from '../components/Footer';

const Home = () => {
  return (
    <>
      <Head>
        <title>EN | LIBRARY</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/KKULogo_1.ico' />
      </Head>

      <Navbar />
      <Main />
      <Booking />
      <Mapping />
      <Footer />
    </>
  );
};

export default Home;
